global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "secure-rest-api-demo"
    metrics_path: /actuator/prometheus
    bearer_token_file: /etc/prometheus/token.txt
    static_configs:
      - targets: ["host.docker.internal:8080"]